### ISSUE TITLE
Support for appleskin

### ISSUE THREAD

**Issue by pizzav-xyz** [plex1on/Simple-Dark#5]
Please make the pack support appleskin.

**Comment by katelyynn** [comment]
this shouldn't be too difficult, will be in the next release!

**Comment by pizzav-xyz** [comment]
> this shouldn't be too difficult, will be in the next release!

can u add this feature  to the 1.12.2 release?

**Comment by katelyynn** [comment]
yeah sure, just make sure to download the `Simple-Dark-(legacy)` file for below 1.13.2! do keep in mind that some of the modded support is still yet to be updated tho (it will use the old design).

release should be up in a bit

**Comment by katelyynn** [comment]
included in https://github.com/plex1on/Simple-Dark/releases/tag/2023.0127!
