### ISSUE TITLE
creative inventory is slightly broken

### ISSUE THREAD

**Issue by paladyn55** [plex1on/Simple-Dark#8]
the gui for the creative inventory doesnt seem to line up properly

![image](https://github.com/kateowo/simple-dark/assets/69397252/ac90bcee-eb16-4c49-88ff-a91673206b95)

**Comment by katelyynn** [comment]
1. which version
2. are u sure u downloaded the correct pack version for ur game version?

in 1.19.4 the creative menu changed

**Comment by paladyn55** [comment]
on 1.20.1, i was using the legacy version because apparently i cant read, using the correct version fixed it

**Comment by katelyynn** [comment]
no worries!!
